### ISSUE TITLE
os.start() - doesn't exist? 

### ISSUE THREAD

**Issue by DennisDyallo** [unifiedremote/Docs#9]
In your section for the lua "os library" you say we can use os.start()
But I cant find anything about os.start() on the internet.

How can I fire and forget an executable from the remote?
https://github.com/unifiedremote/Docs/blob/master/libs/os.md#osstart-command-arg1-arg2--

**Comment by pqvst** [comment]
The reason you can't find anything on the internet is because `os.start()` is a special function added by Unified Remote - it is not a standard Lua os function.

Yes, you can use it fire and forget. Have a look at this example:
https://github.com/unifiedremote/Remotes/blob/master/Examples/Run/remote.lua

**Comment by DennisDyallo** [comment]
Okay, thanks. Sorry! :)
